spring:
#  main:
#    web-application-type: none
#    banner-mode: off
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        stdio: false
        enabled: true

        instructions: "This reactive server provides weather information tools and resources"
        sse-message-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} |%-5level| ${traceId}|${spring.application.name}|[%thread] %logger line:%-3L - %msg%n'
  file:
    name: ./target/spring-ai-mcp-server.demo.log
    path: concreteness/logs
  level:
    org.springframework.ai: debug
    com.example: debug
#logging:
#  level:
#    root: OFF



